### ISSUE TITLE
[1.19] Crusher produces infinite experience

### ISSUE THREAD

**Issue by RavynousHunter** [MikeTheShadow/VoluminousEnergy#108] opened 2022-08-24 15:32 UTC
I have a crusher to which I've attached some Mekanism logistical transporters to automatically store output.  However, when the destination and crusher output are both full, the crusher continues to produce experience as long as there's something inside of it to process, like cinnabar.  With no way to redirect that experience into a tank or some other form of storage, it could easily overwhelm one's world with entities if they aren't paying attention.

Honestly, I'd like if there were a configuration option to disable machines from dropping experience altogether; with no way (that I can find) to store it remotely, it can get annoying, having to stand by your machines as they operate so you don't end up getting lagged out with a bunch of experience orbs.

**Comment by Eelt** [comment] 2022-08-24 17:00
The Crusher should only be spawning in experience orbs when `extractItem` is called, meaning that Mekanism must be constantly trying to extract from the Crusher despite the destination being full (maybe it's calling simulate with the simulate flag set? If so there should be a check to prevent spawning of XP on simulations)

See (0.3): 
https://github.com/MikeTheShadow/VoluminousEnergy/blob/1.19-exp/src/main/java/com/veteam/voluminousenergy/blocks/tiles/CrusherTile.java#L115

See (next):
https://github.com/MikeTheShadow/VoluminousEnergy/blob/1.19-exp-next/src/main/java/com/veteam/voluminousenergy/blocks/tiles/CrusherTile.java#L117

In a future major release (0.4?) the XP will not be hard coded but be determined by recipe, you'll be able to use something like KubeJS to modify the XP values of the recipe to 0.

**Comment by RavynousHunter** [comment] 2022-08-25 23:11
Aah, yeah, I think that's the case.  Thanks for pointing me in the right direction!

**Comment by ProsperCraft** [comment] 2023-03-04 16:31
This is a problem with xnet as well, the output is full in the crusher of bauxite dust, and the xp orbs still come out endlessly.

Could this be fixed by removing xp for crushing bauxite?

**Comment by Eelt** [comment] 2023-03-05 17:42
In 0.4 the XP is configured in the recipe JSON, which is an API break from 0.3. 

As for the root causes, any time another block interfaces into the Crusher's item handler capability and requests an extraction it generates the XP. The issue is most likely that whatever you're piping items into is full, and the mod is trying to extract from the Crusher but gets cancelled. If the amount of items extracted is 0, the XP multiplier (amount * base xp from recipe) should be zero'd, at least in 0.4 builds.

**Comment by Eelt** [comment] 2023-06-12 01:18
I believe this issue has been fixed since 0.4 Alpha 4, if not please re-open.

**Closed as completed by Eelt** 2023-06-12 01:18 UTC
Labels: bug
