### ISSUE TITLE
Crusher crash in 1.19.2

### ISSUE THREAD

**Issue by aAndrew3030** [MikeTheShadow/VoluminousEnergy#109] opened 2023-02-23 03:58 UTC
I have only tried the crusher so far, but it keeps crashing when I try to pull items in or out, or add a multiplier

[crash-2023-02-22_22.41.38-server.txt](https://github.com/MikeTheShadow/VoluminousEnergy/files/10810138/crash-2023-02-22_22.41.38-server.txt)
[crash-2023-02-22_22.51.48-client.txt](https://github.com/MikeTheShadow/VoluminousEnergy/files/10810139/crash-2023-02-22_22.51.48-client.txt)

**Comment by Eelt** [comment] 2023-02-23 04:51
I cannot reproduce this with just a basic mod set (VE, JEI) and you have a lot of mods. I see it's 0.4 Alpha 1a on 1.19 on Forge 43.2.4 which should be fine, but I cannot say if this is some sort of weird mod interaction(?).

I'm going to need all the log files (latest.log, debug.log if you have that), not just your crash reports. Your initial description sounds like you're having this issue when adding items via the GUI?

**Comment by aAndrew3030** [comment] 2023-02-23 07:04
It may be two different mods (or several) causing the same crash with VE (hence two different crash logs I shared above). Going by the second crash report, that shows Sophisticated Core, I was able to recreate the crash with just the Sophisticated mods and VE

[crash-2023-02-23_01.55.06-client.txt](https://github.com/MikeTheShadow/VoluminousEnergy/files/10810997/crash-2023-02-23_01.55.06-client.txt)
[debug.log](https://github.com/MikeTheShadow/VoluminousEnergy/files/10811000/debug.log)

**Comment by Eelt** [comment] 2023-02-24 01:19
Thanks for narrowing down the mods, I'm able to reproduce this crash now.

I'll look into it when I have some more time.

**Comment by Eelt** [comment] 2023-03-04 18:05
Should be fixed in `0.4 Alpha 2` for 1.18.2 and 1.19 releases.

**Closed as completed by Eelt** 2023-03-04 18:05 UTC
Labels: bug, 1.18, 1.19, 0.4
