### ISSUE TITLE
Ore Unification

### ISSUE THREAD

**Issue by enosich** [MikeTheShadow/VoluminousEnergy#9] opened 2020-12-10 01:10 UTC
For the machines provided in the mod, please add support for cross-mod processing support, for instance utilizing forge:ores/copper to create forge:dusts/copper. Perhaps it would be wise to search through forge:ores/* and forge:dusts/* and link them up, same as with other machines.

**Comment by Eelt** [comment] 2020-12-10 02:02
Voluminous Energy actually already (mostly) supports ore unification so long as the ore _exists_ in VE. 

One of the issues in the official releases is actually caused by the fact that only bock tags are used sometimes, and not item tags in certain recipes. Which was fixed in a6d8ab7ad1fcf25f9da0fa20712eeab863fb6e24.

Converting any forge:ore/* to it's respective forge:dusts/* would be a more challenging task (assuming you can't make a JSON with a tag input and tag output, that sounds like weird behaviour in the making) as it's more of the code creating the new recipes in the correct place and time during init when all the items are registered and all the tags are set up BUT the recipes are not registered yet. That would also mean writing quite a few (similar) classes to register recipes (or at least serializers) without access to a JSON file (as it would have to be done internally). This would take some time and effort to do both to code and debug before a release.

**Comment by enosich** [comment] 2020-12-10 04:14
You could try implementing KubeJS support, it should hopefully set recipes up to be scalable, and user-modifiable.

**Comment by Eelt** [comment] 2021-06-20 21:53
Confirmed both KubeJS and CraftTweaker work with making custom crafting recipes with Voluminous Energy (Since 0.1.2.0).

**Closed** 2021-06-20 21:53 UTC
